In [62]:
import numpy as np
import numpy
import pandas as pd
from pandas import read_csv
import warnings
warnings.filterwarnings('ignore')

In [63]:
# load data
SP20 = read_csv('SP20.csv', delimiter=",", low_memory=False, keep_default_na=False)

In [64]:
SP21 = read_csv('SP21.csv', delimiter=",", low_memory=False, keep_default_na=False)

In [65]:
SP20 = SP20[ ['month', 'year', 'SG_UF_NOT','FEBRE','TOSSE','GARGANTA','DISPNEIA','DESC_RESP','DIARREIA','VOMITO',
                  'FADIGA','PERD_OLFT','PERD_PALA', 'CLASSI_FIN'] ]

In [66]:
SP20

,month,year,SG_UF_NOT,FEBRE,TOSSE,GARGANTA,DISPNEIA,DESC_RESP,DIARREIA,VOMITO,FADIGA,PERD_OLFT,PERD_PALA,CLASSI_FIN
0,1,2020,AM,1,1,1,1,1,2,2,2,2,2,0
1,1,2020,AM,1,1,1,1,1,2,2,2,2,2,0
2,1,2020,AM,1,1,1,1,1,2,2,2,2,2,1
3,1,2020,AM,1,1,2,2,2,2,2,2,2,2,1
4,1,2020,AM,1,1,2,2,2,2,2,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,12,2020,AM,1,1,1,1,1,2,1,2,2,2,1
20636,12,2020,AM,1,1,1,1,1,2,2,2,1,1,1
20637,12,2020,AM,2,2,2,1,2,2,2,2,2,2,0
20638,12,2020,AM,1,1,1,1,1,2,2,1,2,2,1
20639,12,2020,AM,1,2,2,1,2,2,2,1,2,2,1

In [67]:
SP21 = SP21[ ['month', 'year', 'SG_UF_NOT','FEBRE','TOSSE','GARGANTA','DISPNEIA','DESC_RESP','DIARREIA','VOMITO',
                  'FADIGA','PERD_OLFT','PERD_PALA', 'CLASSI_FIN'] ]

In [68]:
SP20 = SP20.rename(columns={"FEBRE":"fever", "TOSSE":"cough", "GARGANTA":"throat", 'DISPNEIA':'dyspnoea', 'DESC_RESP': 'respdesc', 'DIARREIA':'diarrhoea', 'VOMITO':'vomit', "FADIGA":"fatigue", 'PERD_OLFT':'lossm', 'PERD_PALA':'losst', "CLASSI_FIN": "res"})

In [69]:
SP21 = SP21.rename(columns={"FEBRE":"fever", "TOSSE":"cough", "GARGANTA":"throat", 'DISPNEIA':'dyspnoea', 'DESC_RESP': 'respdesc', 'DIARREIA':'diarrhoea', 'VOMITO':'vomit', "FADIGA":"fatigue", 'PERD_OLFT':'lossm', 'PERD_PALA':'losst', "CLASSI_FIN": "res"})

In [70]:
SP20

,month,year,SG_UF_NOT,fever,cough,throat,dyspnoea,respdesc,diarrhoea,vomit,fatigue,lossm,losst,res
0,1,2020,AM,1,1,1,1,1,2,2,2,2,2,0
1,1,2020,AM,1,1,1,1,1,2,2,2,2,2,0
2,1,2020,AM,1,1,1,1,1,2,2,2,2,2,1
3,1,2020,AM,1,1,2,2,2,2,2,2,2,2,1
4,1,2020,AM,1,1,2,2,2,2,2,2,2,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20635,12,2020,AM,1,1,1,1,1,2,1,2,2,2,1
20636,12,2020,AM,1,1,1,1,1,2,2,2,1,1,1
20637,12,2020,AM,2,2,2,1,2,2,2,2,2,2,0
20638,12,2020,AM,1,1,1,1,1,2,2,1,2,2,1
20639,12,2020,AM,1,2,2,1,2,2,2,1,2,2,1

In [71]:
SP21

,month,year,SG_UF_NOT,fever,cough,throat,dyspnoea,respdesc,diarrhoea,vomit,fatigue,lossm,losst,res
0,1,2021,AM,1,1,1,1,1,2,2,1,1,1,1
1,1,2021,AM,1,1,1,1,1,2,2,2,2,2,1
2,1,2021,AM,1,2,2,2,1,1,1,2,2,2,1
3,1,2021,AM,1,1,1,1,1,2,2,1,1,1,1
4,1,2021,AM,1,1,2,2,2,2,2,2,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14504,12,2021,AM,2,2,2,2,2,2,2,2,2,2,1
14505,12,2021,AM,1,1,1,2,1,2,2,2,2,2,0
14506,12,2021,AM,1,1,2,1,1,2,2,2,2,2,0
14507,12,2021,AM,2,2,2,1,1,2,2,1,2,2,1
14508,12,2021,AM,1,1,2,1,2,2,2,2,2,2,0

In [72]:
SP20.to_csv("SP20_final.csv", index=False)

In [73]:
SP21.to_csv("SP21_final.csv", index=False)